[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "dg-capture-backend"
version = "0.0.0d"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
